{
  "analysis": "The user wants to complete the 'simple betting app' by making it fully functional. The previous turn provided a detailed plan and most of the necessary files, but `src/App.tsx` was incomplete, specifically the logic for placing bets and resolving events. My task is to finalize `src/App.tsx` to include robust bet placement, event resolution (with random winner selection for demonstration), and balance updates. I will also ensure all components are correctly integrated and the application is ready for preview.",
  "steps": [
    "1. Complete the `handlePlaceBet` function in `src/App.tsx` to correctly create and add a new `PlacedBet` to the state.",
    "2. Implement the `handleResolveEvent` function in `src/App.tsx`. This function will: a) find the target event, b) randomly select one of its outcomes as the winner, c) update the event's status to 'resolved' and set the `winningOutcomeId`, d) iterate through all `placedBets` related to this event, e) determine if each bet won or lost, f) update the bet's status and, if won, add the `potentialPayout` to the user's balance, and g) update the `events` and `placedBets` states.",
    "3. Ensure `src/App.tsx` renders `WalletDisplay`, `EventCard` (for each event), and `PlacedBetsList` with the correct props.",
    "4. Review all provided files for consistency and correct imports, especially `src/lib/utils.ts` for `cn` function usage in UI components.",
    "5. Confirm `package.json`, `index.html`, `tailwind.config.js`, `src/main.tsx`, and `src/index.css` are correctly set up for a React/Tailwind project."
  ],
  "thought": "The core logic resides in `src/App.tsx`. I need to be careful with state updates, especially when resolving events, to ensure immutability and correct balance adjustments. The random winner selection for `handleResolveEvent` will make the demo dynamic. I'll use `setEvents` and `setPlacedBets` with functional updates to correctly modify arrays. Error handling for insufficient balance is already in place, but I'll add a simple `alert` for other edge cases for this 'simple' app.",
  "files": {
    "package.json": "{",
    "  \"name\": \"hello-2-betting-app\",",
    "  \"private\": true,",
    "  \"version\": \"0.0.0\",",
    "  \"type\": \"module\",",
    "  \"scripts\": {",
    "    \"dev\": \"vite\",",
    "    \"build\": \"tsc -b && vite build\",",
    "    \"lint\": \"eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0\",",
    "    \"preview\": \"vite preview\"",
    "  },",
    "  \"dependencies\": {",
    "    \"react\": \"^18.3.1\",",
    "    \"react-dom\": \"^18.3.1\",",
    "    \"lucide-react\": \"^0.408.0\",",
    "    \"clsx\": \"^2.1.1\",",
    "    \"tailwind-merge\": \"^2.4.0\"",
    "  },",
    "  \"devDependencies\": {",
    "    \"@types/react\": \"^18.3.3\",",
    "    \"@types/react-dom\": \"^18.3.0\",",
    "    \"@typescript-eslint/eslint-plugin\": \"^7.13.1\",",
    "    \"@typescript-eslint/parser\": \"^7.13.1\",",
    "    \"@vitejs/plugin-react\": \"^4.3.1\",",
    "    \"autoprefixer\": \"^10.4.19\",",
    "    \"eslint\": \"^8.57.0\",",
    "    \"eslint-plugin-react-hooks\": \"^4.6.2\",",
    "    \"eslint-plugin-react-refresh\": \"^0.4.7\",",
    "    \"postcss\": \"^8.4.39\",",
    "    \"tailwindcss\": \"^4.0.0-next-11\",",
    "    \"typescript\": \"^5.2.2\",",
    "    \"vite\": \"^5.3.1\"",
    "  }",
    "}",
    "index.html": "<!doctype html>",
    "<html lang=\"en\">",
    "  <head>",
    "    <meta charset=\"UTF-8\" />",
    "    <link rel=\"icon\" type=\"image/svg+xml\" href=\"/vite.svg\" />",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />",
    "    <title>Hello 2 - Simple Betting App</title>",
    "  </head>",
    "  <body>",
    "    <div id=\"root\"></div>",
    "    <script type=\"module\" src=\"/src/main.tsx\"></script>",
    "  </body>",
    "</html>",
    "tailwind.config.js": "/** @type {import('tailwindcss').Config} */",
    "export default {",
    "  content: [",
    "    \"./index.html\",",
    "    \"./src/**/*.{js,ts,jsx,tsx}\"",
    "  ],",
    "  theme: {",
    "    extend: {},",
    "  },",
    "  plugins: [],",
    "}",
    "src/main.tsx": "import React from 'react';",
    "import ReactDOM from 'react-dom/client';",
    "import App from './App.tsx';",
    "import './index.css';",
    "",
    "ReactDOM.createRoot(document.getElementById('root')!).render(",
    "  <React.StrictMode>",
    "    <App />",
    "  </React.StrictMode>,",
    ");",
    "src/index.css": "@tailwind base;",
    "@tailwind components;",
    "@tailwind utilities;",
    "",
    "body {",
    "  font-family: 'Inter', sans-serif; /* Example font */",
    "  @apply bg-gray-950 text-gray-50;",
    "}",
    "src/types.ts": "export type Outcome = {",
    "  id: string;",
    "  name: string;",
    "  odds: number; // e.g., 1.5 for 1.5x return",
    "};",
    "",
    "export type EventStatus = 'open' | 'closed' | 'resolved';",
    "",
    "export type BettingEvent = {",
    "  id: string;",
    "  name: string;",
    "  outcomes: Outcome[];",
    "  status: EventStatus;",
    "  winningOutcomeId?: string; // Set when status is 'resolved'",
    "};",
    "",
    "export type BetStatus = 'pending' | 'won' | 'lost';",
    "",
    "export type PlacedBet = {",
    "  id: string;",
    "  eventId: string;",
    "  eventName: string;",
    "  outcomeId: string;",
    "  outcomeName: string;",
    "  odds: number;",
    "  amount: number;",
    "  potentialPayout: number;",
    "  status: BetStatus;",
    "};",
    "src/components/ui/Button.tsx": "import React from 'react';",
    "import { cn } from '../../lib/utils';",
    "",
    "interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {",
    "  variant?: 'default' | 'outline' | 'destructive' | 'ghost';",
    "  size?: 'default' | 'sm' | 'lg' | 'icon';",
    "}",
    "",
    "const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(",
    "  ({ className, variant = 'default', size = 'default', ...props }, ref) => {",
    "    const baseStyles = 'inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50';",
    "",
    "    const variantStyles = {",
    "      default: 'bg-primary text-primary-foreground hover:bg-primary/90'",
    "        + ' bg-blue-600 text-white hover:bg-blue-700',",
    "      outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground'",
    "        + ' border-gray-700 text-gray-200 hover:bg-gray-800',",
    "      destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90'",
    "        + ' bg-red-600 text-white hover:bg-red-700',",
    "      ghost: 'hover:bg-accent hover:text-accent-foreground'",
    "        + ' text-gray-200 hover:bg-gray-800',",
    "    };",
    "",
    "    const sizeStyles = {",
    "      default: 'h-10 px-4 py-2',",
    "      sm: 'h-9 rounded-md px-3',",
    "      lg: 'h-11 rounded-md px-8',",
    "      icon: 'h-10 w-10',",
    "    };",
    "",
    "    return (",
    "      <button",
    "        className={cn(baseStyles, variantStyles[variant], sizeStyles[size], className)}",
    "        ref={ref}",
    "        {...props}",
    "      />",
    "    );",
    "  }",
    ");",
    "Button.displayName = 'Button';",
    "",
    "export { Button };",
    "src/components/ui/Input.tsx": "import React from 'react';",
    "import { cn } from '../../lib/utils';",
    "",
    "export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {}",
    "",
    "const Input = React.forwardRef<HTMLInputElement, InputProps>(",
    "  ({ className, type, ...props }, ref) => {",
    "    return (",
    "      <input",
    "        type={type}",
    "        className={cn(",
    "          'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',",
    "          'border-gray-700 bg-gray-800 text-gray-50 placeholder:text-gray-400 focus-visible:ring-blue-500',",
    "          className",
    "        )}",
    "        ref={ref}",
    "        {...props}",
    "      />",
    "    );",
    "  }",
    ");",
    "Input.displayName = 'Input';",
    "",
    "export { Input };",
    "src/lib/utils.ts": "import { type ClassValue, clsx } from 'clsx';",
    "import { twMerge } from 'tailwind-merge';",
    "",
    "export function cn(...inputs: ClassValue[]) {",
    "  return twMerge(clsx(inputs));",
    "}",
    "src/components/WalletDisplay.tsx": "import React from 'react';",
    "import { Wallet } from 'lucide-react';",
    "",
    "interface WalletDisplayProps {",
    "  balance: number;",
    "}",
    "",
    "const WalletDisplay: React.FC<WalletDisplayProps> = ({ balance }) => {",
    "  return (",
    "    <div className=\"flex items-center gap-2 rounded-lg bg-gray-800 p-3 shadow-md\">",
    "      <Wallet className=\"h-6 w-6 text-green-400\" />",
    "      <span className=\"text-xl font-semibold text-gray-50\">Balance: ${balance.toFixed(2)}</span>",
    "    </div>",
    "  );",
    "};",
    "",
    "export default WalletDisplay;",
    "src/components/EventCard.tsx": "import React, { useState, useMemo } from 'react';",
    "import { BettingEvent, Outcome } from '../types';",
    "import { Button } from './ui/Button';",
    "import { Input } from './ui/Input';",
    "import { DollarSign, CheckCircle, XCircle, Clock } from 'lucide-react';",
    "",
    "interface EventCardProps {",
    "  event: BettingEvent;",
    "  onPlaceBet: (eventId: string, outcomeId: string, amount: number) => void;",
    "  onResolveEvent: (eventId: string) => void;",
    "  userBalance: number; // Added to check balance before placing bet",
    "}",
    "",
    "const EventCard: React.FC<EventCardProps> = ({ event, onPlaceBet, onResolveEvent, userBalance }) => {",
    "  const [selectedOutcomeId, setSelectedOutcomeId] = useState<string | null>(null);",
    "  const [betAmount, setBetAmount] = useState<string>('');",
    "  const [error, setError] = useState<string | null>(null);",
    "",
    "  const selectedOutcome = useMemo(",
    "    () => event.outcomes.find((o) => o.id === selectedOutcomeId),",
    "    [selectedOutcomeId, event.outcomes]",
    "  );",
    "",
    "  const potentialPayout = useMemo(() => {",
    "    const amount = parseFloat(betAmount);",
    "    if (isNaN(amount) || amount <= 0 || !selectedOutcome) return 0;",
    "    return amount * selectedOutcome.odds;",
    "  }, [betAmount, selectedOutcome]);",
    "",
    "  const handlePlaceBet = () => {",
    "    setError(null);",
    "    const amount = parseFloat(betAmount);",
    "    if (!selectedOutcomeId) {",
    "      setError('Please select an outcome.');",
    "      return;",
    "    }",
    "    if (isNaN(amount) || amount <= 0) {",
    "      setError('Please enter a valid bet amount.');",
    "      return;",
    "    }",
    "    if (amount > userBalance) {",
    "      setError('Insufficient balance.');",
    "      return;",
    "    }",
    "    if (event.status !== 'open') {",
    "      setError('This event is no longer open for bets.');",
    "      return;",
    "    }",
    "",
    "    onPlaceBet(event.id, selectedOutcomeId, amount);",
    "    setBetAmount('');",
    "    setSelectedOutcomeId(null);",
    "  };",
    "",
    "  const getStatusIcon = () => {",
    "    switch (event.status) {",
    "      case 'open': return <Clock className=\"h-4 w-4 text-blue-400\" />; ",
    "      case 'closed': return <XCircle className=\"h-4 w-4 text-red-400\" />; ",
    "      case 'resolved': return <CheckCircle className=\"h-4 w-4 text-green-400\" />; ",
    "      default: return null;",
    "    }",
    "  };",
    "",
    "  const getStatusText = () => {",
    "    switch (event.status) {",
    "      case 'open': return 'Open for bets'; ",
    "      case 'closed': return 'Bets closed'; ",
    "      case 'resolved': return `Winner: ${event.outcomes.find(o => o.id === event.winningOutcomeId)?.name || 'N/A'}`; ",
    "      default: return '';",
    "    }",
    "  };",
    "",
    "  return (",
    "    <div className=\"rounded-lg bg-gray-800 p-6 shadow-xl border border-gray-700 flex flex-col gap-4\">",
    "      <div className=\"flex items-center justify-between\">",
    "        <h3 className=\"text-2xl font-bold text-gray-50\">{event.name}</h3>",
    "        <div className=\"flex items-center gap-2 text-sm text-gray-300\">",
    "          {getStatusIcon()}",
    "          <span>{getStatusText()}</span>",
    "        </div>",
    "      </div>",
    "",
    "      <div className=\"grid grid-cols-1 md:grid-cols-2 gap-3\">",
    "        {event.outcomes.map((outcome) => (",
    "          <label",
    "            key={outcome.id}",
    "            className={`flex items-center justify-between p-4 rounded-md cursor-pointer transition-all duration-200",
    "              ${selectedOutcomeId === outcome.id",
    "                ? 'bg-blue-700 border-blue-500 text-white shadow-lg' : 'bg-gray-700 border-gray-600 hover:bg-gray-600 text-gray-200'}",
    "              ${event.status !== 'open' ? 'opacity-70 cursor-not-allowed' : ''}",
    "            `}",
    "          >",
    "            <div className=\"flex items-center gap-2\">",
    "              <input",
    "                type=\"radio\"",
    "                name={`outcome-${event.id}`}",
    "                value={outcome.id}",
    "                checked={selectedOutcomeId === outcome.id}",
    "                onChange={() => event.status === 'open' && setSelectedOutcomeId(outcome.id)}",
    "                className=\"h-5 w-5 text-blue-500 bg-gray-900 border-gray-500 focus:ring-blue-500\"",
    "                disabled={event.status !== 'open'}",
    "              />",
    "              <span className=\"text-lg font-medium\">{outcome.name}</span>",
    "            </div>",
    "            <span className=\"text-xl font-bold text-green-300\">{outcome.odds.toFixed(2)}x</span>",
    "          </label>",
    "        ))}",
    "      </div>",
    "",
    "      {event.status === 'open' && (",
    "        <div className=\"flex flex-col gap-3\">",
    "          <div className=\"flex items-center gap-3\">",
    "            <Input",
    "              type=\"number\"",
    "              placeholder=\"Bet amount\"",
    "              value={betAmount}",
    "              onChange={(e) => {",
    "                setBetAmount(e.target.value);",
    "                setError(null);",
    "              }}",
    "              min=\"0.01\"",
    "              step=\"0.01\"",
    "              className=\"flex-grow\"",
    "            />",
    "            <Button onClick={handlePlaceBet} disabled={!selectedOutcomeId || parseFloat(betAmount) <= 0 || parseFloat(betAmount) > userBalance}>",
    "              <DollarSign className=\"h-4 w-4 mr-2\" /> Place Bet",
    "            </Button>",
    "          </div>",
    "          {potentialPayout > 0 && (",
    "            <p className=\"text-sm text-gray-300\">",
    "              Potential Payout: <span className=\"font-semibold text-green-400\">${potentialPayout.toFixed(2)}</span>",
    "            </p>",
    "          )}",
    "          {error && <p className=\"text-red-400 text-sm\">{error}</p>}",
    "        </div>",
    "      )}",
    "",
    "      {event.status === 'open' && (",
    "        <Button",
    "          variant=\"outline\"",
    "          onClick={() => onResolveEvent(event.id)}",
    "          className=\"mt-2 w-full\"",
    "        >",
    "          Resolve Event (Demo)",
    "        </Button>",
    "      )}",
    "    </div>",
    "  );",
    "};",
    "",
    "export default EventCard;",
    "src/components/PlacedBetsList.tsx": "import React from 'react';",
    "import { PlacedBet, BetStatus } from '../types';",
    "import { CheckCircle, XCircle, Clock } from 'lucide-react';",
    "",
    "interface PlacedBetsListProps {",
    "  bets: PlacedBet[];",
    "}",
    "",
    "const getStatusIcon = (status: BetStatus) => {",
    "  switch (status) {",
    "    case 'pending': return <Clock className=\"h-4 w-4 text-blue-400\" />; ",
    "    case 'won': return <CheckCircle className=\"h-4 w-4 text-green-400\" />; ",
    "    case 'lost': return <XCircle className=\"h-4 w-4 text-red-400\" />; ",
    "    default: return null;",
    "  }",
    "};",
    "",
    "const PlacedBetsList: React.FC<PlacedBetsListProps> = ({ bets }) => {",
    "  if (bets.length === 0) {",
    "    return (",
    "      <div className=\"rounded-lg bg-gray-800 p-6 text-center text-gray-400 border border-gray-700\">",
    "        No bets placed yet.",
    "      </div>",
    "    );",
    "  }",
    "",
    "  return (",
    "    <div className=\"rounded-lg bg-gray-800 p-6 shadow-xl border border-gray-700\">",
    "      <h2 className=\"text-2xl font-bold mb-4 text-gray-50\">Your Placed Bets</h2>",
    "      <div className=\"space-y-4\">",
    "        {bets.map((bet) => (",
    "          <div",
    "            key={bet.id}",
    "            className={`flex flex-col sm:flex-row items-start sm:items-center justify-between p-4 rounded-md",
    "              ${bet.status === 'won' ? 'bg-green-900/40 border-green-700' : ''}",
    "              ${bet.status === 'lost' ? 'bg-red-900/40 border-red-700' : ''}",
    "              ${bet.status === 'pending' ? 'bg-gray-700 border-gray-600' : ''}",
    "              border",
    "            `}",
    "          >",
    "            <div className=\"flex flex-col mb-2 sm:mb-0\">",
    "              <p className=\"text-lg font-semibold text-gray-50\">",
    "                {bet.eventName} - <span className=\"text-blue-300\">{bet.outcomeName}</span>",
    "              </p>",
    "              <p className=\"text-sm text-gray-300\">",
    "                Bet: <span className=\"font-medium text-white\">${bet.amount.toFixed(2)}</span> @ {bet.odds.toFixed(2)}x",
    "              </p>",
    "            </div>",
    "            <div className=\"flex items-center gap-3\">",
    "              <div className=\"flex items-center gap-1 text-sm font-medium\">",
    "                {getStatusIcon(bet.status)}",
    "                <span className={`capitalize ${bet.status === 'won' ? 'text-green-300' : bet.status === 'lost' ? 'text-red-300' : 'text-blue-300'}`}>",
    "                  {bet.status}",
    "                </span>",
    "              </div>",
    "              {bet.status === 'won' && (",
    "                <span className=\"text-lg font-bold text-green-400\">+${bet.potentialPayout.toFixed(2)}</span>",
    "              )}",
    "              {bet.status === 'lost' && (",
    "                <span className=\"text-lg font-bold text-red-400\">-${bet.amount.toFixed(2)}</span>",
    "              )}",
    "              {bet.status === 'pending' && (",
    "                <span className=\"text-lg font-bold text-gray-300\">Payout: ${bet.potentialPayout.toFixed(2)}</span>",
    "              )}",
    "            </div>",
    "          </div>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "};",
    "",
    "export default PlacedBetsList;",
    "src/App.tsx": "import React, { useState, useCallback } from 'react';",
    "import { BettingEvent, PlacedBet } from './types';",
    "import WalletDisplay from './components/WalletDisplay';",
    "import EventCard from './components/EventCard';",
    "import PlacedBetsList from './components/PlacedBetsList';",
    "",
    "const initialEvents: BettingEvent[] = [",
    "  {",
    "    id: 'event-1',",
    "    name: 'Football Match: Team A vs Team B',",
    "    outcomes: [",
    "      { id: 'outcome-1-1', name: 'Team A Wins', odds: 2.10 },",
    "      { id: 'outcome-1-2', name: 'Draw', odds: 3.50 },",
    "      { id: 'outcome-1-3', name: 'Team B Wins', odds: 3.00 },",
    "    ],",
    "    status: 'open',",
    "  },",
    "  {",
    "    id: 'event-2',",
    "    name: 'Basketball Game: Lakers vs Celtics',",
    "    outcomes: [",
    "      { id: 'outcome-2-1', name: 'Lakers Win', odds: 1.80 },",
    "      { id: 'outcome-2-2', name: 'Celtics Win', odds: 2.20 },",
    "    ],",
    "    status: 'open',",
    "  },",
    "  {",
    "    id: 'event-3',",
    "    name: 'Esports: League of Legends Finals',",
    "    outcomes: [",
    "      { id: 'outcome-3-1', name: 'T1 Wins', odds: 1.65 },",
    "      { id: 'outcome-3-2', name: 'Gen.G Wins', odds: 2.50 },",
    "    ],",
    "    status: 'open',",
    "  },",
    "];",
    "",
    "function App() {",
    "  const [balance, setBalance] = useState<number>(1000);",
    "  const [events, setEvents] = useState<BettingEvent[]>(initialEvents);",
    "  const [placedBets, setPlacedBets] = useState<PlacedBet[]>([]);",
    "",
    "  const handlePlaceBet = useCallback((eventId: string, outcomeId: string, amount: number) => {",
    "    const event = events.find((e) => e.id === eventId);",
    "    const outcome = event?.outcomes.find((o) => o.id === outcomeId);",
    "",
    "    if (!event || !outcome) {",
    "      alert('Error: Event or outcome not found.');",
    "      return;",
    "    }",
    "",
    "    if (event.status !== 'open') {",
    "      alert('This event is no longer open for bets.');",
    "      return;",
    "    }",
    "",
    "    if (amount <= 0) {",
    "      alert('Bet amount must be positive.');",
    "      return;",
    "    }",
    "",
    "    if (balance < amount) {",
    "      alert('Insufficient balance to place this bet.');",
    "      return;",
    "    }",
    "",
    "    setBalance((prev) => prev - amount);",
    "",
    "    const newBet: PlacedBet = {",
    "      id: crypto.randomUUID(),",
    "      eventId: event.id,",
    "      eventName: event.name,",
    "      outcomeId: outcome.id,",
    "      outcomeName: outcome.name,",
    "      odds: outcome.odds,",
    "      amount: amount,",
    "      potentialPayout: amount * outcome.odds,",
    "      status: 'pending',",
    "    };",
    "",
    "    setPlacedBets((prev) => [...prev, newBet]);",
    "    alert(`Bet placed successfully! Bet: $${amount.toFixed(2)} on ${outcome.name}. Potential payout: $${newBet.potentialPayout.toFixed(2)}`);",
    "  }, [balance, events]);",
    "",
    "  const handleResolveEvent = useCallback((eventId: string) => {",
    "    setEvents((prevEvents) => {",
    "      const updatedEvents = prevEvents.map((event) => {",
    "        if (event.id === eventId) {",
    "          if (event.status !== 'open') {",
    "            alert('Event is not open to be resolved.');",
    "            return event;",
    "          }",
    "          const winningOutcome = event.outcomes[Math.floor(Math.random() * event.outcomes.length)];",
    "          return { ...event, status: 'resolved', winningOutcomeId: winningOutcome.id };",
    "        }",
    "        return event;",
    "      });",
    "      return updatedEvents;",
    "    });",
    "",
    "    setPlacedBets((prevBets) => {",
    "      let totalWinnings = 0;",
    "      const updatedBets = prevBets.map((bet) => {",
    "        if (bet.eventId === eventId && bet.status === 'pending') {",
    "          const resolvedEvent = events.find((e) => e.id === eventId && e.status === 'resolved');",
    "          if (resolvedEvent && resolvedEvent.winningOutcomeId) {",
    "            if (bet.outcomeId === resolvedEvent.winningOutcomeId) {",
    "              totalWinnings += bet.potentialPayout;",
    "              return { ...bet, status: 'won' };",
    "            } else {",
    "              return { ...bet, status: 'lost' };",
    "            }",
    "          }",
    "        }",
    "        return bet;",
    "      });",
    "",
    "      if (totalWinnings > 0) {",
    "        setBalance((prev) => prev + totalWinnings);",
    "        alert(`Event resolved! You won $${totalWinnings.toFixed(2)}!`);",
    "      } else {",
    "        alert('Event resolved! No winnings from this event or no bets placed on winning outcome.');",
    "      }",
    "      return updatedBets;",
    "    });",
    "  }, [events]); // Dependency on 'events' to get the latest resolved event state",
    "",
    "  return (",
    "    <div className=\"min-h-screen bg-gray-950 text-gray-50 p-4 sm:p-8\">",
    "      <header className=\"flex flex-col sm:flex-row justify-between items-center mb-8